export const initUserObj = {
    address: "",
    admin: 0,
    premises: 0,
    boughtProducts: {},
    city: "",
    country: "",
    date: "",
    email: "",
    finishedRegistration: false,
    company: {
        ico: "",
        dic: "",
        icdph: "",
        address: '',
        psc: '',
        country: '',
    },
    lenses: {
        cylinder: [],
        cylinderAxes: [],
        diopters: [],
        distance: [],
        addition: [],
        basis: [],
        prism: [],
    },
    name: "",
    orders: [],
    phone: "",
    psc: "",
    tempUser: false,
    totalSpent: 0,
    watchList: [],
    fName: "",
    lName: "",
    password: '',
    confirmPassword: "",
    birthDate: Date.now(),
    optometrist: false

}