export const initUserObj = {
    address: "",
    admin: 0,
    boughtProducts: {},
    city: "",
    country: "",
    date: "",
    email: "",
    finishedRegistration: false,
    lenses: {
        cylinder: [0, 0],
        cylinderAxes: [0, 0],
        diopters: [0, 0],
        distance: [0, 0],
    },
    name: "",
    orders: [],
    phone: "",
    psc: "",
    tempUser: false,
    totalSpent: 0,
    watchList: [],
    fName: "",
    lName: ""
}